import Contracts.Common

namespace src

open Verity hiding pure bind
open Contracts
open Verity.EVM.Uint256
open Verity.Stdlib.Math

-- This starter is intentionally small: it shows the full Tama path from a
-- Verity contract, to Lean specs/proofs, to generated bytecode and Foundry
-- tests. The contract is ERC20-shaped, but omits allowances and events so the
-- proof surface stays readable.
verity_contract ERC20Lite where
  storage
    -- Storage slots are explicit. The generated manifest records these slots
    -- so `tama audit storage-layout` can compare Lean and compiler artifacts.
    ownerSlot : Address := slot 0
    balancesSlot : Address → Uint256 := slot 1
    totalSupplySlot : Uint256 := slot 2

  constructor (initialOwner : Address) := do
    setStorageAddr ownerSlot initialOwner
    setStorage totalSupplySlot 0

  -- Only the deployment owner can mint. `safeAdd` returns `none` on overflow,
  -- and `requireSomeUint` turns that into a revert.
  function mint (toAddr : Address, amount : Uint256) : Bool := do
    let sender ← msgSender
    let currentOwner ← getStorageAddr ownerSlot
    require (sender == currentOwner) "Caller is not the owner"
    let currentBalance ← getMapping balancesSlot toAddr
    let newBalance ← requireSomeUint (safeAdd currentBalance amount) "Balance overflow"
    let currentSupply ← getStorage totalSupplySlot
    let newSupply ← requireSomeUint (safeAdd currentSupply amount) "Supply overflow"
    setMapping balancesSlot toAddr newBalance
    setStorage totalSupplySlot newSupply
    return true

  -- Transfers preserve total supply. The self-transfer branch avoids a
  -- read/modify/write round trip that would otherwise double-count.
  function transfer (toAddr : Address, amount : Uint256) : Bool := do
    let sender ← msgSender
    let senderBalance ← getMapping balancesSlot sender
    require (senderBalance >= amount) "Insufficient balance"
    if sender == toAddr then
      pure ()
    else
      let recipientBalance ← getMapping balancesSlot toAddr
      let newRecipientBalance ← requireSomeUint (safeAdd recipientBalance amount) "Recipient balance overflow"
      setMapping balancesSlot sender (sub senderBalance amount)
      setMapping balancesSlot toAddr newRecipientBalance
    return true

  function view balanceOf (addr : Address) : Uint256 := do
    let currentBalance ← getMapping balancesSlot addr
    return currentBalance

  function view totalSupply () : Uint256 := do
    let currentSupply ← getStorage totalSupplySlot
    return currentSupply

  function view owner () : Address := do
    let currentOwner ← getStorageAddr ownerSlot
    return currentOwner

  -- Ownership transfer: only the current owner can promote a successor. The
  -- proof obligation pair below shows both halves of access control: the
  -- authorized path actually rotates the slot, and the unauthorized path
  -- leaves it untouched.
  --
  -- This starter intentionally does NOT reject `newOwner = 0`. A
  -- production Ownable contract would add a `require (newOwner != 0)
  -- "..."` check (and a corresponding `transferOwnership_rejects_zero`
  -- spec); we keep the starter minimal so the access-control
  -- demonstration stays focused on one property at a time.
  function transferOwnership (newOwner : Address) : Unit := do
    let sender ← msgSender
    let currentOwner ← getStorageAddr ownerSlot
    require (sender == currentOwner) "Caller is not the owner"
    setStorageAddr ownerSlot newOwner

end src
